language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install bundler

# Disable support for sudo to get faster builds with Docker
sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - ruby-head

notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: always
