dist: bionic

language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby
  - ruby-head

notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: always
